sudo: false
language: node_js
node_js:
  - "6"
cache:
  directories: node_modules
branches:
  only: master

before_install:
  - npm prune
  - export CHROME_BIN=chromium-browser
  - "npm i -g npm@^3"
# install:
#   - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_failure:
  - cat /home/travis/build/fulls1z3/ng2-config/npm-debug.log

notifications:
  email: true
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always